[package]
name = "pointwise-gen"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "3.3.2"
anyhow = "1.0.44"
env_logger = "0.9.0"
log = "0.4.14"
paw = "1.0.0"
serde = { version = "1.0.130", features = ["derive"] }
serde_json = "1.0.68"
serde_yaml = "0.8.21"
structopt = { version = "0.3.23", features = ["paw"] }
ttf-parser = "0.12.3"
url = { version = "2.2.2", features = ["serde"] }
