[package]
name = "pointwise-gen"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.44"
env_logger = "0.9.0"
log = "0.4.14"
paw = "1.0.0"
serde = { version = "1.0.130", features = ["derive"] }
serde_json = "1.0.68"
structopt = { version = "0.3.23", features = ["paw"] }
ttf-parser = { version = "0.13.2", features = ["variable-fonts"] }
pointwise-common = { path = "../common" }
lyon_algorithms = "0.17.6"
lyon_path = "0.17.7"
