[package]
name = "gen"
version = "0.1.0"
edition = "2021"
default-run = "gen"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.95"
env_logger = "0.11.6"
log = "0.4.25"
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.138"
ttf-parser = { version = "0.25.1", features = ["variable-fonts"] }
chrono = { version = "0.4.39", features = ["serde", "now"] }
pulldown-cmark = "0.12.2"
git2 = "0.20.0"
regex = "1.11.1"
lyon_algorithms = "1.0.5"
lyon_path = "1.0.6"
clap = { version = "4.5.27", features = ["derive"] }
ts-rs = { version = "10.1.0" }
syntect = "5.2.0"
atom_syndication = "0.12.6"
url = "2.5.4"
unicode-segmentation = "1.12.0"
unicode-linebreak = "0.1.5"
tempfile = "3.16.0"
itertools = "0.14.0"
katex = "0.4.6"
notify-debouncer-full = "0.5.0"
typst = "0.13.1"
rayon = "1.10.0"
scraper = "0.24.0"

[build-dependencies]
syntect = "5.2.0"
